# Generated by Django 2.2 on 2021-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
