# Generated by Django 2.2 on 2021-09-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210905_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
