# Generated by Django 2.2 on 2021-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210904_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='like',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
    ]
