# Generated by Django 2.2 on 2021-09-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210904_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='user.UserModel', verbose_name='Лайкнул'),
        ),
    ]
