# Generated by Django 2.2 on 2021-09-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210904_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
