# Generated by Django 2.2 on 2021-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_likemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
